
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getPayment_id_6e9ccc8b31
ROOST_METHOD_SIG_HASH=getPayment_id_6308770b57

[
  {
    "description": "getPayment_id() returns the current value of the payment_id field after it is set via setPayment_id(int).",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "getPayment_id() returns the positive value (e.g., 12345) previously set via setPayment_id(int).",
    "category": "critical",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "getPayment_id() returns zero when payment_id is set to 0 via setPayment_id(int).",
    "category": "critical",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "getPayment_id() returns a negative value (e.g., -999) previously set via setPayment_id(int).",
    "category": "critical",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "getPayment_id() returns the default value (0) when setPayment_id(int) has not been called.",
    "category": "critical",
    "source": "llm",
    "priority": "medium"
  }
]
*/

// ********RoostGPT********

package com.beko.DemoBank_v1.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.time.LocalDateTime;

public class PaymentGetPaymentIdTest {

	@Test
	void testGetPaymentId_ReturnsPositiveInt() {
		Payment payment = new Payment();
		payment.setPayment_id(12345);
		assertEquals(12345, payment.getPayment_id());
	}

	@Test
	void testGetPaymentId_ReturnsZero() {
		Payment payment = new Payment();
		payment.setPayment_id(0);
		assertEquals(0, payment.getPayment_id());
	}

	@Test
	void testGetPaymentId_ReturnsNegativeInt() {
		Payment payment = new Payment();
		payment.setPayment_id(-999);
		assertEquals(-999, payment.getPayment_id());
	}

	@Test
	void testGetPaymentId_ReturnsDefaultValueBeforeSet() {
		Payment payment = new Payment();
		assertEquals(0, payment.getPayment_id());
	}

}