
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getPayment_id_6e9ccc8b31
ROOST_METHOD_SIG_HASH=getPayment_id_6308770b57

[
  {
    "name": "getPayment_id_isIndependentOfOtherFields",
    "category": "state",
    "goal": "Verify getPayment_id is not affected by unrelated field updates.",
    "setup": [
      "Populate payment_id with representative value; set all other fields to non-defaults."
    ],
    "assertions": [
      "Assert getPayment_id still returns the expected value for payment_id."
    ],
    "mocks": [],
    "priority": "medium",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsNegativeValue",
    "category": "boundary",
    "goal": "Verify getPayment_id preserves a negative numeric value.",
    "setup": [
      "Set payment_id to -1."
    ],
    "assertions": [
      "Assert the getter returns -1 without transformation."
    ],
    "mocks": [],
    "priority": "high",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsZeroValue",
    "category": "boundary",
    "goal": "Verify getPayment_id returns zero when the field is explicitly set to zero.",
    "setup": [
      "Set payment_id to 0."
    ],
    "assertions": [
      "Assert the getter returns 0."
    ],
    "mocks": [],
    "priority": "medium",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_isIndependentOfOtherFields",
    "category": "state",
    "goal": "Verify getPayment_id is not affected by unrelated field updates.",
    "setup": [
      "Populate other fields with representative values."
    ],
    "assertions": [
      "Assert getPayment_id still returns the expected value for payment_id."
    ],
    "mocks": [],
    "priority": "medium",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsDefaultValue",
    "category": "default",
    "goal": "Verify getPayment_id returns the default value before any state is changed.",
    "setup": [],
    "assertions": [
      "Assert the returned int matches the default state."
    ],
    "mocks": [],
    "priority": "high",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsDefaultValue",
    "category": "default",
    "goal": "Verify getPayment_id returns the default value before any state is changed.",
    "setup": [],
    "assertions": [
      "Assert the returned int matches the default state (0 for primitive int)."
    ],
    "mocks": [],
    "priority": "high",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsLatestAssignedValue",
    "category": "state",
    "goal": "Verify getPayment_id returns the latest value after repeated updates.",
    "setup": [
      "Call setPayment_id multiple times with different values."
    ],
    "assertions": [
      "Assert the getter returns the last assigned value."
    ],
    "mocks": [],
    "priority": "high",
    "source": "seeded"
  },
  {
    "name": "getPayment_id_returnsLatestAssignedValue",
    "category": "state",
    "goal": "Verify getPayment_id returns the latest value after repeated updates.",
    "setup": [
      "Call setPayment_id multiple times with different values; check after the last assignment."
    ],
    "assertions": [
      "Assert the getter returns the last assigned value."
    ],
    "mocks": [],
    "priority": "high",
    "source": "seeded"
  }
]
*/

// ********RoostGPT********

package com.beko.DemoBank_v1.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.time.LocalDateTime;
import org.junit.jupiter.api.*;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

class PaymentHistoryGetPaymentIdTest {

	@Test
	void getPayment_id_returnsDefaultValue() {
		PaymentHistory paymentHistory = new PaymentHistory();
		assertEquals(0, paymentHistory.getPayment_id(), "Default int field should be 0");
	}

	@Test
	void getPayment_id_returnsNegativeValue() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(-1);
		assertEquals(-1, paymentHistory.getPayment_id(), "Getter should return negative value set");
	}

	@Test
	void getPayment_id_returnsZeroValue() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(0);
		assertEquals(0, paymentHistory.getPayment_id(), "Getter should return zero value set");
	}

	@Test
	void getPayment_id_returnsPositiveValue() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(12345);
		assertEquals(12345, paymentHistory.getPayment_id(), "Getter should return positive value set");
	}

	@Test
	void getPayment_id_returnsMaxBoundary() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(Integer.MAX_VALUE);
		assertEquals(Integer.MAX_VALUE, paymentHistory.getPayment_id(), "Getter should return Integer.MAX_VALUE");
	}

	@Test
	void getPayment_id_returnsMinBoundary() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(Integer.MIN_VALUE);
		assertEquals(Integer.MIN_VALUE, paymentHistory.getPayment_id(), "Getter should return Integer.MIN_VALUE");
	}

	@Test
	void getPayment_id_returnsLatestAssignedValue() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(10);
		paymentHistory.setPayment_id(77);
		assertEquals(77, paymentHistory.getPayment_id(), "Getter should return last assigned value");
	}

	@Test
	void getPayment_id_isIndependentOfOtherFields() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(42);
		paymentHistory.setAccount_id(1001);
		paymentHistory.setBeneficiary("Alice");
		paymentHistory.setBeneficiary_acc_no("BEN123456");
		paymentHistory.setAmount(250.50);
		paymentHistory.setReference_no("REF2024");
		paymentHistory.setStatus("SUCCESS");
		paymentHistory.setReason_code("RC_OK");
		paymentHistory.setCreated_at(LocalDateTime.now());
		assertEquals(42, paymentHistory.getPayment_id(), "Getter should return payment_id regardless of other fields");
	}

}