
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-demo using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getPayment_id_6e9ccc8b31
ROOST_METHOD_SIG_HASH=getPayment_id_6308770b57

[
  {
    "description": "getPayment_id() returns 0 after explicitly setting payment_id to 0 via setPayment_id(0) on PaymentHistory.",
    "category": "critical",
    "source": "llm",
    "priority": "high"
  },
  {
    "description": "getPayment_id() returns the most recent value set via multiple calls to setPayment_id(int) on the same PaymentHistory instance.",
    "category": "recommended",
    "source": "llm",
    "priority": "medium"
  },
  {
    "description": "getPayment_id() returns 0 when payment_id is unset after PaymentHistory is constructed with the default constructor.",
    "category": "critical",
    "source": "source",
    "priority": "high"
  },
  {
    "description": "getPayment_id() returns the value previously set by setPayment_id(int) after assigning a positive integer value.",
    "category": "critical",
    "source": "source",
    "priority": "high"
  },
  {
    "description": "getPayment_id() returns the value previously set by setPayment_id(int) after assigning a negative integer value.",
    "category": "recommended",
    "source": "source",
    "priority": "medium"
  },
  {
    "description": "getPayment_id() returns the value previously set by setPayment_id(int) after assigning zero.",
    "category": "recommended",
    "source": "source",
    "priority": "medium"
  }
]
*/

// ********RoostGPT********

package com.beko.DemoBank_v1.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.*;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDateTime;

public class PaymentHistoryGetPaymentIdTest {

	@Test
	void returnsZeroForDefaultPaymentHistoryId() {
		PaymentHistory paymentHistory = new PaymentHistory();
		Assertions.assertEquals(0, paymentHistory.getPayment_id());
	}

	@Test
	void returnsSetPositivePaymentHistoryId() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(123);
		Assertions.assertEquals(123, paymentHistory.getPayment_id());
	}

	@Test
	void returnsSetNegativePaymentHistoryId() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(-42);
		Assertions.assertEquals(-42, paymentHistory.getPayment_id());
	}

	@Test
	void returnsSetZeroPaymentHistoryId() {
		PaymentHistory paymentHistory = new PaymentHistory();
		paymentHistory.setPayment_id(0);
		Assertions.assertEquals(0, paymentHistory.getPayment_id());
	}

}